env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: 'module'
  project: './tsconfig.json'
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
rules:
  'react/prop-types': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/explicit-module-boundary-types':
    - 'warn'
    - allowArgumentsExplicitlyTypedAsAny: true
  '@typescript-eslint/prefer-optional-chain': 'error'
  '@typescript-eslint/prefer-nullish-coalescing': 'error'
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/no-redeclare': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'error'
  'import/no-named-as-default': 'off'
  'import/no-named-as-default-member': 'off'
  'import/order':
    - 'warn'
    - 'alphabetize':
        'order': 'asc'
